version: "3.7"
services:
  web:
    working_dir: /home
    environment:
      FLASK_DEBUG: 1
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    volumes:
      - .:/home
